plugins:
    - "@trivago/prettier-plugin-sort-imports"
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrder:
    - "<BUILTIN_MODULES>"
    - "<THIRD_PARTY_MODULES>"
    - "^\\.\\./(.*)$"
    - "^\\./(.*)$"
